/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.user.infra.db.jooq;


import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserDbTable;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserRoleDbTable;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserRolesDbTable;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:08B786DD10ED37B5B7DCA0FA63C996E8",
        "schema version:auth_user_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> AUTH_USER_EMAIL_UQC = Internal.createUniqueKey(AuthUserDbTable.AUTH_USER_DB_TABLE, DSL.name("auth_user_email_uqc"), new TableField[] { AuthUserDbTable.AUTH_USER_DB_TABLE.EMAIL }, true);
    public static final UniqueKey<Record> AUTH_USER_PKEY = Internal.createUniqueKey(AuthUserDbTable.AUTH_USER_DB_TABLE, DSL.name("auth_user_pkey"), new TableField[] { AuthUserDbTable.AUTH_USER_DB_TABLE.ID }, true);
    public static final UniqueKey<Record> AUTH_USER_ROLE_PKEY = Internal.createUniqueKey(AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE, DSL.name("auth_user_role_pkey"), new TableField[] { AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE.ID }, true);
    public static final UniqueKey<Record> AUTH_USER_ROLE_LINK_USER_ROLE_UQ = Internal.createUniqueKey(AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, DSL.name("auth_user_role_link_user_role_uq"), new TableField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.USER_ID, AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ROLE_ID }, true);
    public static final UniqueKey<Record> AUTH_USER_ROLES_PKEY = Internal.createUniqueKey(AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, DSL.name("auth_user_roles_pkey"), new TableField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_ROLE_ID_FK = Internal.createForeignKey(AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, DSL.name("auth_user_role_link_role_id_fk"), new TableField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ROLE_ID, AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ROLE_ID }, Keys.AUTH_USER_ROLE_PKEY, new TableField[] { AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE.ID, AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<Record, Record> AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_USER_ID_FK = Internal.createForeignKey(AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, DSL.name("auth_user_role_link_user_id_fk"), new TableField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.USER_ID, AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.USER_ID }, Keys.AUTH_USER_PKEY, new TableField[] { AuthUserDbTable.AUTH_USER_DB_TABLE.ID, AuthUserDbTable.AUTH_USER_DB_TABLE.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
