/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.user.infra.db.jooq;


import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserDbTable;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserRoleDbTable;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserRolesDbTable;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:54602A3D09EA1D17203E7F81729044DF",
        "schema version:auth_user_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.auth_user</code>.
     */
    public final AuthUserDbTable AUTH_USER_DB_TABLE = AuthUserDbTable.AUTH_USER_DB_TABLE;

    /**
     * The table <code>public.auth_user_role</code>.
     */
    public final AuthUserRoleDbTable AUTH_USER_ROLE_DB_TABLE = AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE;

    /**
     * The table <code>public.auth_user_roles</code>.
     */
    public final AuthUserRolesDbTable AUTH_USER_ROLES_DB_TABLE = AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AuthUserDbTable.AUTH_USER_DB_TABLE,
            AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE,
            AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE
        );
    }
}
