/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.user.infra.db.jooq.tables;


import com.petromirdzhunev.user.infra.db.jooq.Indexes;
import com.petromirdzhunev.user.infra.db.jooq.Keys;
import com.petromirdzhunev.user.infra.db.jooq.Public;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserRolesDbTable.AuthUserRolesPath;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:54602A3D09EA1D17203E7F81729044DF",
        "schema version:auth_user_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthUserDbTable extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auth_user</code>
     */
    public static final AuthUserDbTable AUTH_USER_DB_TABLE = new AuthUserDbTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.auth_user.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.auth_user.email</code>.
     */
    public final TableField<Record, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.auth_user.password</code>.
     */
    public final TableField<Record, String> PASSWORD = createField(DSL.name("password"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.auth_user.first_name</code>.
     */
    public final TableField<Record, String> FIRST_NAME = createField(DSL.name("first_name"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.auth_user.last_name</code>.
     */
    public final TableField<Record, String> LAST_NAME = createField(DSL.name("last_name"), SQLDataType.VARCHAR(128).nullable(false).defaultValue(DSL.field(DSL.raw("''::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.auth_user.created_at</code>.
     */
    public final TableField<Record, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.auth_user.created_by</code>.
     */
    public final TableField<Record, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    private AuthUserDbTable(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthUserDbTable(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.auth_user</code> table reference
     */
    public AuthUserDbTable(String alias) {
        this(DSL.name(alias), AUTH_USER_DB_TABLE);
    }

    /**
     * Create an aliased <code>public.auth_user</code> table reference
     */
    public AuthUserDbTable(Name alias) {
        this(alias, AUTH_USER_DB_TABLE);
    }

    /**
     * Create a <code>public.auth_user</code> table reference
     */
    public AuthUserDbTable() {
        this(DSL.name("auth_user"), null);
    }

    public <O extends Record> AuthUserDbTable(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, AUTH_USER_DB_TABLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.21.6",
            "configuration hash:54602A3D09EA1D17203E7F81729044DF",
            "schema version:auth_user_definition.sql"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AuthUserPath extends AuthUserDbTable implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuthUserPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuthUserPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthUserPath as(String alias) {
            return new AuthUserPath(DSL.name(alias), this);
        }

        @Override
        public AuthUserPath as(Name alias) {
            return new AuthUserPath(alias, this);
        }

        @Override
        public AuthUserPath as(Table<?> alias) {
            return new AuthUserPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTH_USER_EMAIL_IDX, Indexes.AUTH_USER_EMAIL_UQC, Indexes.AUTH_USER_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.AUTH_USER_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.AUTH_USER_EMAIL_UQC);
    }

    private transient AuthUserRolesPath _authUserRoles;

    /**
     * Get the implicit to-many join path to the
     * <code>public.auth_user_roles</code> table
     */
    public AuthUserRolesPath authUserRoles() {
        if (_authUserRoles == null)
            _authUserRoles = new AuthUserRolesPath(this, null, Keys.AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_USER_ID_FK.getInverseKey());

        return _authUserRoles;
    }

    @Override
    public AuthUserDbTable as(String alias) {
        return new AuthUserDbTable(DSL.name(alias), this);
    }

    @Override
    public AuthUserDbTable as(Name alias) {
        return new AuthUserDbTable(alias, this);
    }

    @Override
    public AuthUserDbTable as(Table<?> alias) {
        return new AuthUserDbTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserDbTable rename(String name) {
        return new AuthUserDbTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserDbTable rename(Name name) {
        return new AuthUserDbTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserDbTable rename(Table<?> name) {
        return new AuthUserDbTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserDbTable where(Condition condition) {
        return new AuthUserDbTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserDbTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserDbTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserDbTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserDbTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserDbTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserDbTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserDbTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserDbTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserDbTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
