/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.user.infra.db.jooq.tables;


import com.petromirdzhunev.user.infra.db.jooq.Indexes;
import com.petromirdzhunev.user.infra.db.jooq.Keys;
import com.petromirdzhunev.user.infra.db.jooq.Public;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserDbTable.AuthUserPath;
import com.petromirdzhunev.user.infra.db.jooq.tables.AuthUserRoleDbTable.AuthUserRolePath;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:54602A3D09EA1D17203E7F81729044DF",
        "schema version:auth_user_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthUserRolesDbTable extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auth_user_roles</code>
     */
    public static final AuthUserRolesDbTable AUTH_USER_ROLES_DB_TABLE = new AuthUserRolesDbTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.auth_user_roles.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.auth_user_roles.user_id</code>.
     */
    public final TableField<Record, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.auth_user_roles.role_id</code>.
     */
    public final TableField<Record, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AuthUserRolesDbTable(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthUserRolesDbTable(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.auth_user_roles</code> table reference
     */
    public AuthUserRolesDbTable(String alias) {
        this(DSL.name(alias), AUTH_USER_ROLES_DB_TABLE);
    }

    /**
     * Create an aliased <code>public.auth_user_roles</code> table reference
     */
    public AuthUserRolesDbTable(Name alias) {
        this(alias, AUTH_USER_ROLES_DB_TABLE);
    }

    /**
     * Create a <code>public.auth_user_roles</code> table reference
     */
    public AuthUserRolesDbTable() {
        this(DSL.name("auth_user_roles"), null);
    }

    public <O extends Record> AuthUserRolesDbTable(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, AUTH_USER_ROLES_DB_TABLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.21.6",
            "configuration hash:54602A3D09EA1D17203E7F81729044DF",
            "schema version:auth_user_definition.sql"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AuthUserRolesPath extends AuthUserRolesDbTable implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuthUserRolesPath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuthUserRolesPath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthUserRolesPath as(String alias) {
            return new AuthUserRolesPath(DSL.name(alias), this);
        }

        @Override
        public AuthUserRolesPath as(Name alias) {
            return new AuthUserRolesPath(alias, this);
        }

        @Override
        public AuthUserRolesPath as(Table<?> alias) {
            return new AuthUserRolesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTH_USER_ROLE_LINK_ROLE_ID_IDX, Indexes.AUTH_USER_ROLE_LINK_USER_ID_IDX, Indexes.AUTH_USER_ROLE_LINK_USER_ROLE_UQ, Indexes.AUTH_USER_ROLES_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.AUTH_USER_ROLES_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.AUTH_USER_ROLE_LINK_USER_ROLE_UQ);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.asList(Keys.AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_ROLE_ID_FK, Keys.AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_USER_ID_FK);
    }

    private transient AuthUserRolePath _authUserRole;

    /**
     * Get the implicit join path to the <code>public.auth_user_role</code>
     * table.
     */
    public AuthUserRolePath authUserRole() {
        if (_authUserRole == null)
            _authUserRole = new AuthUserRolePath(this, Keys.AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_ROLE_ID_FK, null);

        return _authUserRole;
    }

    private transient AuthUserPath _authUser;

    /**
     * Get the implicit join path to the <code>public.auth_user</code> table.
     */
    public AuthUserPath authUser() {
        if (_authUser == null)
            _authUser = new AuthUserPath(this, Keys.AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_USER_ID_FK, null);

        return _authUser;
    }

    @Override
    public AuthUserRolesDbTable as(String alias) {
        return new AuthUserRolesDbTable(DSL.name(alias), this);
    }

    @Override
    public AuthUserRolesDbTable as(Name alias) {
        return new AuthUserRolesDbTable(alias, this);
    }

    @Override
    public AuthUserRolesDbTable as(Table<?> alias) {
        return new AuthUserRolesDbTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRolesDbTable rename(String name) {
        return new AuthUserRolesDbTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRolesDbTable rename(Name name) {
        return new AuthUserRolesDbTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRolesDbTable rename(Table<?> name) {
        return new AuthUserRolesDbTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRolesDbTable where(Condition condition) {
        return new AuthUserRolesDbTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRolesDbTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRolesDbTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRolesDbTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRolesDbTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRolesDbTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRolesDbTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRolesDbTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRolesDbTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRolesDbTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
