/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.vehicle.infra.db.jooq;


import com.petromirdzhunev.vehicle.infra.db.jooq.tables.VehicleDbTable;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:CB482A17531799A2B03E3255DB1B0F99",
        "schema version:vehicle_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index VEHICLE_PKEY = Internal.createIndex(DSL.name("vehicle_pkey"), VehicleDbTable.VEHICLE_DB_TABLE, new OrderField[] { VehicleDbTable.VEHICLE_DB_TABLE.ID }, true);
    public static final Index VEHICLE_PLATE_IDX = Internal.createIndex(DSL.name("vehicle_plate_idx"), VehicleDbTable.VEHICLE_DB_TABLE, new OrderField[] { VehicleDbTable.VEHICLE_DB_TABLE.PLATE }, false);
    public static final Index VEHICLE_PLATE_UQC = Internal.createIndex(DSL.name("vehicle_plate_uqc"), VehicleDbTable.VEHICLE_DB_TABLE, new OrderField[] { VehicleDbTable.VEHICLE_DB_TABLE.PLATE }, true);
    public static final Index VEHICLE_TYPE_IDX = Internal.createIndex(DSL.name("vehicle_type_idx"), VehicleDbTable.VEHICLE_DB_TABLE, new OrderField[] { VehicleDbTable.VEHICLE_DB_TABLE.TYPE }, false);
    public static final Index VEHICLE_VIN_IDX = Internal.createIndex(DSL.name("vehicle_vin_idx"), VehicleDbTable.VEHICLE_DB_TABLE, new OrderField[] { VehicleDbTable.VEHICLE_DB_TABLE.VIN }, false);
    public static final Index VEHICLE_VIN_UQC = Internal.createIndex(DSL.name("vehicle_vin_uqc"), VehicleDbTable.VEHICLE_DB_TABLE, new OrderField[] { VehicleDbTable.VEHICLE_DB_TABLE.VIN }, true);
}
