/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.vehicle.infra.db.jooq;


import com.petromirdzhunev.vehicle.infra.db.jooq.tables.VehicleDbTable;

import javax.annotation.processing.Generated;

import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:3149B230179E38A7A789D42ECB302B5B",
        "schema version:vehicle_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> VEHICLE_PKEY = Internal.createUniqueKey(VehicleDbTable.VEHICLE_DB_TABLE, DSL.name("vehicle_pkey"), new TableField[] { VehicleDbTable.VEHICLE_DB_TABLE.ID }, true);
    public static final UniqueKey<Record> VEHICLE_PLATE_UQC = Internal.createUniqueKey(VehicleDbTable.VEHICLE_DB_TABLE, DSL.name("vehicle_plate_uqc"), new TableField[] { VehicleDbTable.VEHICLE_DB_TABLE.PLATE }, true);
    public static final UniqueKey<Record> VEHICLE_VIN_UQC = Internal.createUniqueKey(VehicleDbTable.VEHICLE_DB_TABLE, DSL.name("vehicle_vin_uqc"), new TableField[] { VehicleDbTable.VEHICLE_DB_TABLE.VIN }, true);
}
