/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.vehicle.infra.db.jooq;


import com.petromirdzhunev.vehicle.infra.db.jooq.tables.VehicleDbTable;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:CB482A17531799A2B03E3255DB1B0F99",
        "schema version:vehicle_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.vehicle</code>.
     */
    public final VehicleDbTable VEHICLE_DB_TABLE = VehicleDbTable.VEHICLE_DB_TABLE;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            VehicleDbTable.VEHICLE_DB_TABLE
        );
    }
}
