/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.vehicle.infra.db.jooq;


import com.petromirdzhunev.vehicle.infra.db.jooq.tables.VehicleDbTable;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:3149B230179E38A7A789D42ECB302B5B",
        "schema version:vehicle_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.vehicle</code>.
     */
    public static final VehicleDbTable VEHICLE_DB_TABLE = VehicleDbTable.VEHICLE_DB_TABLE;
}
