/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.petromirdzhunev.user.infra.http.server.controller;

import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.petromirdzhunev.user.infra.http.server.controller.model.LoginRequestPayload;
import com.petromirdzhunev.user.infra.http.server.controller.model.LoginResponsePayload;
import com.petromirdzhunev.user.infra.http.server.controller.model.UserCreationRequestPayload;
import com.petromirdzhunev.user.infra.http.server.controller.model.UserCreationResponsePayload;
import com.petromirdzhunev.user.infra.http.server.controller.model.UserResponsePayload;

import jakarta.annotation.Generated;
import jakarta.validation.Valid;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.23.0")
@Validated
public interface UsersApi {

    String PATH_AUTHENTICATED_USER = "/api/users/self";
    /**
     * GET /api/users/self : Authenticated user details
     * Retrieve user details
     *
     * @return Successful login (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = UsersApi.PATH_AUTHENTICATED_USER,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    UserResponsePayload authenticatedUser(
        
    );


    String PATH_CREATE_USER = "/api/users";
    /**
     * POST /api/users : Create a user
     *
     * @param userCreationRequestPayload  (required)
     * @return User created successfully (status code 201)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = UsersApi.PATH_CREATE_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    UserCreationResponsePayload createUser(
         @Valid @RequestBody UserCreationRequestPayload userCreationRequestPayload
    );


    String PATH_DELETE_USER = "/api/users/{id}";
    /**
     * DELETE /api/users/{id} : Delete a specific user by id
     *
     * @param id ID of the user (required)
     * @return Flow deleted successfully (status code 204)
     *         or Unauthorized (status code 401)
     *         or User not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = UsersApi.PATH_DELETE_USER,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteUser(
         @PathVariable("id") Long id
    );


    String PATH_LOGIN = "/api/users/login";
    /**
     * POST /api/users/login : User login
     * Authenticates a user with a username and password, returning a JWT token if successful.
     *
     * @param loginRequestPayload  (required)
     * @return Successful login (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = UsersApi.PATH_LOGIN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    LoginResponsePayload login(
         @Valid @RequestBody LoginRequestPayload loginRequestPayload
    );

}
