/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.vehicle.infra.db.jooq.tables;


import com.petromirdzhunev.vehicle.infra.db.jooq.Indexes;
import com.petromirdzhunev.vehicle.infra.db.jooq.Keys;
import com.petromirdzhunev.vehicle.infra.db.jooq.Public;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:CB482A17531799A2B03E3255DB1B0F99",
        "schema version:vehicle_definition.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class VehicleDbTable extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.vehicle</code>
     */
    public static final VehicleDbTable VEHICLE_DB_TABLE = new VehicleDbTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.vehicle.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.vehicle.type</code>.
     */
    public final TableField<Record, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.vehicle.year</code>.
     */
    public final TableField<Record, Integer> YEAR = createField(DSL.name("year"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.vehicle.make</code>.
     */
    public final TableField<Record, String> MAKE = createField(DSL.name("make"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.vehicle.model</code>.
     */
    public final TableField<Record, String> MODEL = createField(DSL.name("model"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.vehicle.plate</code>.
     */
    public final TableField<Record, String> PLATE = createField(DSL.name("plate"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.vehicle.vin</code>.
     */
    public final TableField<Record, String> VIN = createField(DSL.name("vin"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.vehicle.nickname</code>.
     */
    public final TableField<Record, String> NICKNAME = createField(DSL.name("nickname"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.vehicle.created_at</code>.
     */
    public final TableField<Record, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.vehicle.created_by</code>.
     */
    public final TableField<Record, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    private VehicleDbTable(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private VehicleDbTable(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.vehicle</code> table reference
     */
    public VehicleDbTable(String alias) {
        this(DSL.name(alias), VEHICLE_DB_TABLE);
    }

    /**
     * Create an aliased <code>public.vehicle</code> table reference
     */
    public VehicleDbTable(Name alias) {
        this(alias, VEHICLE_DB_TABLE);
    }

    /**
     * Create a <code>public.vehicle</code> table reference
     */
    public VehicleDbTable() {
        this(DSL.name("vehicle"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.VEHICLE_PKEY, Indexes.VEHICLE_PLATE_IDX, Indexes.VEHICLE_PLATE_UQC, Indexes.VEHICLE_TYPE_IDX, Indexes.VEHICLE_VIN_IDX, Indexes.VEHICLE_VIN_UQC);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.VEHICLE_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getUniqueKeys() {
        return Arrays.asList(Keys.VEHICLE_PLATE_UQC, Keys.VEHICLE_VIN_UQC);
    }

    @Override
    public List<Check<Record>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("vehicle_type_chk"), "(((type)::text = ANY ((ARRAY['CAR'::character varying, 'TRUCK'::character varying, 'MOTORCYCLE'::character varying, 'SUV'::character varying, 'VAN'::character varying, 'OTHER'::character varying])::text[])))", true)
        );
    }

    @Override
    public VehicleDbTable as(String alias) {
        return new VehicleDbTable(DSL.name(alias), this);
    }

    @Override
    public VehicleDbTable as(Name alias) {
        return new VehicleDbTable(alias, this);
    }

    @Override
    public VehicleDbTable as(Table<?> alias) {
        return new VehicleDbTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleDbTable rename(String name) {
        return new VehicleDbTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleDbTable rename(Name name) {
        return new VehicleDbTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public VehicleDbTable rename(Table<?> name) {
        return new VehicleDbTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleDbTable where(Condition condition) {
        return new VehicleDbTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleDbTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleDbTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleDbTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleDbTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleDbTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleDbTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public VehicleDbTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleDbTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public VehicleDbTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
