/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.users.infra.db.jooq;


import com.petromirdzhunev.users.infra.db.jooq.tables.AuthUserDbTable;
import com.petromirdzhunev.users.infra.db.jooq.tables.AuthUserRoleDbTable;
import com.petromirdzhunev.users.infra.db.jooq.tables.AuthUserRolesDbTable;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:C21653A8B1B0FF360E2A9813563CD906",
        "schema version:Init.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUTH_USER_EMAIL_IDX = Internal.createIndex(DSL.name("auth_user_email_idx"), AuthUserDbTable.AUTH_USER_DB_TABLE, new OrderField[] { AuthUserDbTable.AUTH_USER_DB_TABLE.EMAIL }, false);
    public static final Index AUTH_USER_EMAIL_UQC = Internal.createIndex(DSL.name("auth_user_email_uqc"), AuthUserDbTable.AUTH_USER_DB_TABLE, new OrderField[] { AuthUserDbTable.AUTH_USER_DB_TABLE.EMAIL }, true);
    public static final Index AUTH_USER_PKEY = Internal.createIndex(DSL.name("auth_user_pkey"), AuthUserDbTable.AUTH_USER_DB_TABLE, new OrderField[] { AuthUserDbTable.AUTH_USER_DB_TABLE.ID }, true);
    public static final Index AUTH_USER_ROLE_LINK_ROLE_ID_IDX = Internal.createIndex(DSL.name("auth_user_role_link_role_id_idx"), AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, new OrderField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ROLE_ID }, false);
    public static final Index AUTH_USER_ROLE_LINK_USER_ID_IDX = Internal.createIndex(DSL.name("auth_user_role_link_user_id_idx"), AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, new OrderField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.USER_ID }, false);
    public static final Index AUTH_USER_ROLE_LINK_USER_ROLE_UQ = Internal.createIndex(DSL.name("auth_user_role_link_user_role_uq"), AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, new OrderField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.USER_ID, AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ROLE_ID }, true);
    public static final Index AUTH_USER_ROLE_PKEY = Internal.createIndex(DSL.name("auth_user_role_pkey"), AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE, new OrderField[] { AuthUserRoleDbTable.AUTH_USER_ROLE_DB_TABLE.ID }, true);
    public static final Index AUTH_USER_ROLES_PKEY = Internal.createIndex(DSL.name("auth_user_roles_pkey"), AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE, new OrderField[] { AuthUserRolesDbTable.AUTH_USER_ROLES_DB_TABLE.ID }, true);
}
