/*
 * This file is generated by jOOQ.
 */
package com.petromirdzhunev.users.infra.db.jooq.tables;


import com.petromirdzhunev.users.infra.db.jooq.Indexes;
import com.petromirdzhunev.users.infra.db.jooq.Keys;
import com.petromirdzhunev.users.infra.db.jooq.Public;
import com.petromirdzhunev.users.infra.db.jooq.tables.AuthUserRolesDbTable.AuthUserRolesPath;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.21.6",
        "configuration hash:C21653A8B1B0FF360E2A9813563CD906",
        "schema version:Init.sql"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AuthUserRoleDbTable extends TableImpl<Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.auth_user_role</code>
     */
    public static final AuthUserRoleDbTable AUTH_USER_ROLE_DB_TABLE = new AuthUserRoleDbTable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.auth_user_role.id</code>.
     */
    public final TableField<Record, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.auth_user_role.code</code>.
     */
    public final TableField<Record, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>public.auth_user_role.name</code>.
     */
    public final TableField<Record, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private AuthUserRoleDbTable(Name alias, Table<Record> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AuthUserRoleDbTable(Name alias, Table<Record> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.auth_user_role</code> table reference
     */
    public AuthUserRoleDbTable(String alias) {
        this(DSL.name(alias), AUTH_USER_ROLE_DB_TABLE);
    }

    /**
     * Create an aliased <code>public.auth_user_role</code> table reference
     */
    public AuthUserRoleDbTable(Name alias) {
        this(alias, AUTH_USER_ROLE_DB_TABLE);
    }

    /**
     * Create a <code>public.auth_user_role</code> table reference
     */
    public AuthUserRoleDbTable() {
        this(DSL.name("auth_user_role"), null);
    }

    public <O extends Record> AuthUserRoleDbTable(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
        super(path, childPath, parentPath, AUTH_USER_ROLE_DB_TABLE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    @Generated(
        value = {
            "https://www.jooq.org",
            "jOOQ version:3.21.6",
            "configuration hash:C21653A8B1B0FF360E2A9813563CD906",
            "schema version:Init.sql"
        },
        comments = "This class is generated by jOOQ"
    )
    public static class AuthUserRolePath extends AuthUserRoleDbTable implements Path<Record> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AuthUserRolePath(Table<O> path, ForeignKey<O, Record> childPath, InverseForeignKey<O, Record> parentPath) {
            super(path, childPath, parentPath);
        }
        private AuthUserRolePath(Name alias, Table<Record> aliased) {
            super(alias, aliased);
        }

        @Override
        public AuthUserRolePath as(String alias) {
            return new AuthUserRolePath(DSL.name(alias), this);
        }

        @Override
        public AuthUserRolePath as(Name alias) {
            return new AuthUserRolePath(alias, this);
        }

        @Override
        public AuthUserRolePath as(Table<?> alias) {
            return new AuthUserRolePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AUTH_USER_ROLE_PKEY);
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.AUTH_USER_ROLE_PKEY;
    }

    private transient AuthUserRolesPath _authUserRoles;

    /**
     * Get the implicit to-many join path to the
     * <code>public.auth_user_roles</code> table
     */
    public AuthUserRolesPath authUserRoles() {
        if (_authUserRoles == null)
            _authUserRoles = new AuthUserRolesPath(this, null, Keys.AUTH_USER_ROLES__AUTH_USER_ROLE_LINK_ROLE_ID_FK.getInverseKey());

        return _authUserRoles;
    }

    @Override
    public AuthUserRoleDbTable as(String alias) {
        return new AuthUserRoleDbTable(DSL.name(alias), this);
    }

    @Override
    public AuthUserRoleDbTable as(Name alias) {
        return new AuthUserRoleDbTable(alias, this);
    }

    @Override
    public AuthUserRoleDbTable as(Table<?> alias) {
        return new AuthUserRoleDbTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRoleDbTable rename(String name) {
        return new AuthUserRoleDbTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRoleDbTable rename(Name name) {
        return new AuthUserRoleDbTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuthUserRoleDbTable rename(Table<?> name) {
        return new AuthUserRoleDbTable(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRoleDbTable where(Condition condition) {
        return new AuthUserRoleDbTable(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRoleDbTable where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRoleDbTable where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRoleDbTable where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRoleDbTable where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRoleDbTable where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRoleDbTable where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AuthUserRoleDbTable where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRoleDbTable whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AuthUserRoleDbTable whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
