/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.petromirdzhunev.vehicle.infra.http.server.controller;

import com.petromirdzhunev.vehicle.infra.http.server.controller.model.VehicleRequestPayload;
import com.petromirdzhunev.vehicle.infra.http.server.controller.model.VehicleResponsePayload;
import org.springframework.http.HttpStatus;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", comments = "Generator version: 7.23.0")
@Validated
public interface VehiclesApi {

    String PATH_CREATE_VEHICLE = "/api/vehicles";
    /**
     * POST /api/vehicles : Create a vehicle
     * Registers a new vehicle for the authenticated user&#39;s household.
     *
     * @param vehicleRequestPayload  (required)
     * @return Vehicle created successfully (status code 201)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.POST,
        value = VehiclesApi.PATH_CREATE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.CREATED)
    VehicleResponsePayload createVehicle(
         @Valid @RequestBody VehicleRequestPayload vehicleRequestPayload
    );


    String PATH_DELETE_VEHICLE = "/api/vehicles/{id}";
    /**
     * DELETE /api/vehicles/{id} : Delete a specific vehicle by id
     * Decommissions a vehicle, removing it from the household.
     *
     * @param id ID of the vehicle (required)
     * @return Vehicle deleted successfully (status code 204)
     *         or Unauthorized (status code 401)
     *         or Vehicle not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = VehiclesApi.PATH_DELETE_VEHICLE,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.NO_CONTENT)
    void deleteVehicle(
         @PathVariable("id") Long id
    );


    String PATH_GET_VEHICLE = "/api/vehicles/{id}";
    /**
     * GET /api/vehicles/{id} : Retrieve a specific vehicle by id
     *
     * @param id ID of the vehicle (required)
     * @return Vehicle retrieved successfully (status code 200)
     *         or Unauthorized (status code 401)
     *         or Vehicle not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = VehiclesApi.PATH_GET_VEHICLE,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    VehicleResponsePayload getVehicle(
         @PathVariable("id") Long id
    );


    String PATH_LIST_VEHICLES = "/api/vehicles";
    /**
     * GET /api/vehicles : List vehicles
     * Returns all vehicles registered to the authenticated user&#39;s household.
     *
     * @return Vehicles retrieved successfully (status code 200)
     *         or Unauthorized (status code 401)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.GET,
        value = VehiclesApi.PATH_LIST_VEHICLES,
        produces = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    List<VehicleResponsePayload> listVehicles(
        
    );


    String PATH_UPDATE_VEHICLE = "/api/vehicles/{id}";
    /**
     * PUT /api/vehicles/{id} : Update a specific vehicle by id
     * Replaces the mutable fields of an existing vehicle.
     *
     * @param id ID of the vehicle (required)
     * @param vehicleRequestPayload  (required)
     * @return Vehicle updated successfully (status code 200)
     *         or Unauthorized (status code 401)
     *         or Vehicle not found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @RequestMapping(
        method = RequestMethod.PUT,
        value = VehiclesApi.PATH_UPDATE_VEHICLE,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    @ResponseStatus(HttpStatus.OK)
    VehicleResponsePayload updateVehicle(
         @PathVariable("id") Long id,
         @Valid @RequestBody VehicleRequestPayload vehicleRequestPayload
    );

}
